// Ethiopian Food Database - 40+ items
export const ethiopianFoods = [
  // Breakfast items
  {
    name_en: 'Teff Porridge (Injera Firfir)',
    name_am: 'ተፍ ወላወል',
    calories_per_serving: 280,
    protein_g: 9,
    carbs_g: 52,
    fat_g: 2,
    serving_description: '1 cup cooked',
    is_fasting_friendly: true,
    category: 'breakfast',
    image_url: '/foods/teff-porridge.jpg',
  },
  {
    name_en: 'Injera (Flatbread)',
    name_am: 'እንጀራ',
    calories_per_serving: 220,
    protein_g: 6,
    carbs_g: 42,
    fat_g: 1,
    serving_description: '1 injera sheet',
    is_fasting_friendly: true,
    category: 'breakfast',
    image_url: '/foods/injera.jpg',
  },
  {
    name_en: 'Kinche (Cereal)',
    name_am: 'ኪንቼ',
    calories_per_serving: 320,
    protein_g: 10,
    carbs_g: 60,
    fat_g: 3,
    serving_description: '1 cup cooked',
    is_fasting_friendly: true,
    category: 'breakfast',
    image_url: '/foods/kinche.jpg',
  },
  {
    name_en: 'Genfo (Barley Porridge)',
    name_am: 'ገንፎ',
    calories_per_serving: 350,
    protein_g: 12,
    carbs_g: 58,
    fat_g: 6,
    serving_description: '1 serving (with butter)',
    is_fasting_friendly: false,
    category: 'breakfast',
    image_url: '/foods/genfo.jpg',
  },
  {
    name_en: 'Ful (Fava Beans)',
    name_am: 'ፉል',
    calories_per_serving: 280,
    protein_g: 8,
    carbs_g: 35,
    fat_g: 8,
    serving_description: '1 cup cooked',
    is_fasting_friendly: true,
    category: 'breakfast',
    image_url: '/foods/ful.jpg',
  },
  {
    name_en: 'Enkulal Firfir (Egg Bread)',
    name_am: 'እንቁላል ፍርፍር',
    calories_per_serving: 380,
    protein_g: 18,
    carbs_g: 38,
    fat_g: 16,
    serving_description: '1 serving',
    is_fasting_friendly: false,
    category: 'breakfast',
    image_url: '/foods/enkulal-firfir.jpg',
  },

  // Lunch/Dinner items
  {
    name_en: 'Doro Wot (Chicken Stew)',
    name_am: 'ዶሮ ወጥ',
    calories_per_serving: 420,
    protein_g: 35,
    carbs_g: 15,
    fat_g: 22,
    serving_description: '1 plate (with injera)',
    is_fasting_friendly: false,
    category: 'lunch',
    image_url: '/foods/doro-wot.jpg',
  },
  {
    name_en: 'Misir Wot (Lentil Stew)',
    name_am: 'ምስር ���ጥ',
    calories_per_serving: 280,
    protein_g: 12,
    carbs_g: 42,
    fat_g: 6,
    serving_description: '1 plate (with injera)',
    is_fasting_friendly: true,
    category: 'lunch',
    image_url: '/foods/misir-wot.jpg',
  },
  {
    name_en: 'Shiro (Chickpea Paste)',
    name_am: 'ሽሮ',
    calories_per_serving: 320,
    protein_g: 14,
    carbs_g: 35,
    fat_g: 12,
    serving_description: '1 plate',
    is_fasting_friendly: true,
    category: 'lunch',
    image_url: '/foods/shiro.jpg',
  },
  {
    name_en: 'Tibs (Sautéed Meat)',
    name_am: 'ጢብስ',
    calories_per_serving: 480,
    protein_g: 42,
    carbs_g: 8,
    fat_g: 28,
    serving_description: '1 plate',
    is_fasting_friendly: false,
    category: 'lunch',
    image_url: '/foods/tibs.jpg',
  },
  {
    name_en: 'Gored Gored (Raw Meat)',
    name_am: 'ጎረደ ጎረደ',
    calories_per_serving: 550,
    protein_g: 48,
    carbs_g: 2,
    fat_g: 38,
    serving_description: '1 portion',
    is_fasting_friendly: false,
    category: 'lunch',
    image_url: '/foods/gored-gored.jpg',
  },
  {
    name_en: 'Dulet (Tripe Stew)',
    name_am: 'ዱሌት',
    calories_per_serving: 380,
    protein_g: 36,
    carbs_g: 12,
    fat_g: 20,
    serving_description: '1 plate',
    is_fasting_friendly: false,
    category: 'lunch',
    image_url: '/foods/dulet.jpg',
  },
  {
    name_en: 'Derek Tibs (Dry Sautéed Meat)',
    name_am: 'ደረቅ ጢብስ',
    calories_per_serving: 500,
    protein_g: 44,
    carbs_g: 5,
    fat_g: 32,
    serving_description: '1 plate',
    is_fasting_friendly: false,
    category: 'lunch',
    image_url: '/foods/derek-tibs.jpg',
  },
  {
    name_en: 'Yetsom Beyaynetu (Fasting Platter)',
    name_am: 'የጾም በአይነቱ',
    calories_per_serving: 350,
    protein_g: 14,
    carbs_g: 48,
    fat_g: 10,
    serving_description: '1 mixed plate',
    is_fasting_friendly: true,
    category: 'lunch',
    image_url: '/foods/yetsom-beyaynetu.jpg',
  },
  {
    name_en: 'Beyaynetu (Mixed Platter)',
    name_am: 'በአይነቱ',
    calories_per_serving: 480,
    protein_g: 32,
    carbs_g: 42,
    fat_g: 20,
    serving_description: '1 mixed plate',
    is_fasting_friendly: false,
    category: 'lunch',
    image_url: '/foods/beyaynetu.jpg',
  },
  {
    name_en: 'Firfir (Bread in Sauce)',
    name_am: 'ፍርፍር',
    calories_per_serving: 360,
    protein_g: 10,
    carbs_g: 45,
    fat_g: 14,
    serving_description: '1 plate',
    is_fasting_friendly: true,
    category: 'lunch',
    image_url: '/foods/firfir.jpg',
  },
  {
    name_en: 'Kategna (Fried Bread)',
    name_am: 'ካተግና',
    calories_per_serving: 420,
    protein_g: 8,
    carbs_g: 48,
    fat_g: 22,
    serving_description: '2 pieces',
    is_fasting_friendly: true,
    category: 'lunch',
    image_url: '/foods/kategna.jpg',
  },
  {
    name_en: 'Chechebsa (Butter Bread)',
    name_am: 'ቸቸብሳ',
    calories_per_serving: 440,
    protein_g: 10,
    carbs_g: 50,
    fat_g: 22,
    serving_description: '1 serving',
    is_fasting_friendly: false,
    category: 'lunch',
    image_url: '/foods/chechebsa.jpg',
  },
  {
    name_en: 'Kitfo (Minced Raw Meat)',
    name_am: 'ክትፎ',
    calories_per_serving: 520,
    protein_g: 46,
    carbs_g: 4,
    fat_g: 36,
    serving_description: '1 portion',
    is_fasting_friendly: false,
    category: 'lunch',
    image_url: '/foods/kitfo.jpg',
  },

  // Snacks
  {
    name_en: 'Sambusa (Fried Pastry)',
    name_am: 'ሳምቡሳ',
    calories_per_serving: 280,
    protein_g: 8,
    carbs_g: 28,
    fat_g: 14,
    serving_description: '2 sambusakas',
    is_fasting_friendly: false,
    category: 'snack',
    image_url: '/foods/sambusa.jpg',
  },
  {
    name_en: 'Ayib (Fresh Cheese)',
    name_am: 'አይብ',
    calories_per_serving: 180,
    protein_g: 20,
    carbs_g: 6,
    fat_g: 8,
    serving_description: '1 cup',
    is_fasting_friendly: false,
    category: 'snack',
    image_url: '/foods/ayib.jpg',
  },
  {
    name_en: 'Chikla (Corn Snack)',
    name_am: 'ጫክላ',
    calories_per_serving: 320,
    protein_g: 10,
    carbs_g: 55,
    fat_g: 4,
    serving_description: '1 cup roasted',
    is_fasting_friendly: true,
    category: 'snack',
    image_url: '/foods/chikla.jpg',
  },
  {
    name_en: 'Kolo (Roasted Barley)',
    name_am: 'ቆሎ',
    calories_per_serving: 340,
    protein_g: 12,
    carbs_g: 52,
    fat_g: 6,
    serving_description: '1 cup',
    is_fasting_friendly: true,
    category: 'snack',
    image_url: '/foods/kolo.jpg',
  },
  {
    name_en: 'Popcorn',
    name_am: 'ፖፕኮርን',
    calories_per_serving: 100,
    protein_g: 3,
    carbs_g: 10,
    fat_g: 5,
    serving_description: '1 small bag',
    is_fasting_friendly: true,
    category: 'snack',
    image_url: '/foods/popcorn.jpg',
  },
  {
    name_en: 'Ethiopian Honey Cake',
    name_am: 'መቅለት',
    calories_per_serving: 380,
    protein_g: 6,
    carbs_g: 62,
    fat_g: 12,
    serving_description: '1 slice',
    is_fasting_friendly: true,
    category: 'snack',
    image_url: '/foods/honey-cake.jpg',
  },

  // Vegetables & Sides
  {
    name_en: 'Gomen (Collard Greens)',
    name_am: 'ጎመን',
    calories_per_serving: 140,
    protein_g: 4,
    carbs_g: 18,
    fat_g: 6,
    serving_description: '1 plate',
    is_fasting_friendly: true,
    category: 'lunch',
    image_url: '/foods/gomen.jpg',
  },
  {
    name_en: 'Derfo (Cabbage)',
    name_am: 'ደርፎ',
    calories_per_serving: 120,
    protein_g: 3,
    carbs_g: 22,
    fat_g: 2,
    serving_description: '1 plate',
    is_fasting_friendly: true,
    category: 'lunch',
    image_url: '/foods/derfo.jpg',
  },
  {
    name_en: 'Misir Potata (Split Peas & Potatoes)',
    name_am: 'ምስር ጣታ',
    calories_per_serving: 220,
    protein_g: 8,
    carbs_g: 38,
    fat_g: 3,
    serving_description: '1 plate',
    is_fasting_friendly: true,
    category: 'lunch',
    image_url: '/foods/misir-potata.jpg',
  },
  {
    name_en: 'Teff Injera (Regular)',
    name_am: 'ተፍ እንጀራ',
    calories_per_serving: 220,
    protein_g: 6,
    carbs_g: 42,
    fat_g: 1,
    serving_description: '1 sheet',
    is_fasting_friendly: true,
    category: 'breakfast',
    image_url: '/foods/teff-injera.jpg',
  },
  {
    name_en: 'Barley Injera',
    name_am: 'ገብ እንጀራ',
    calories_per_serving: 200,
    protein_g: 6,
    carbs_g: 38,
    fat_g: 2,
    serving_description: '1 sheet',
    is_fasting_friendly: true,
    category: 'breakfast',
    image_url: '/foods/barley-injera.jpg',
  },
  {
    name_en: 'Moringa Leaf Sauce',
    name_am: 'ሞሪንጋ',
    calories_per_serving: 80,
    protein_g: 4,
    carbs_g: 12,
    fat_g: 1,
    serving_description: '1 serving',
    is_fasting_friendly: true,
    category: 'lunch',
    image_url: '/foods/moringa.jpg',
  },
  {
    name_en: 'Shiro Legume Mix',
    name_am: 'ሽሮ ድብልቅ',
    calories_per_serving: 310,
    protein_g: 16,
    carbs_g: 36,
    fat_g: 10,
    serving_description: '1 plate',
    is_fasting_friendly: true,
    category: 'lunch',
    image_url: '/foods/shiro-mix.jpg',
  },
  {
    name_en: 'Kik Alicha (Mild Lentils)',
    name_am: 'ክክ አልቻ',
    calories_per_serving: 240,
    protein_g: 10,
    carbs_g: 40,
    fat_g: 3,
    serving_description: '1 plate',
    is_fasting_friendly: true,
    category: 'lunch',
    image_url: '/foods/kik-alicha.jpg',
  },
  {
    name_en: 'Wot with Vegetables',
    name_am: 'ወጥ ዛፍ',
    calories_per_serving: 280,
    protein_g: 8,
    carbs_g: 38,
    fat_g: 10,
    serving_description: '1 plate',
    is_fasting_friendly: true,
    category: 'lunch',
    image_url: '/foods/vegetable-wot.jpg',
  },
  {
    name_en: 'Egg Scramble (Fried Eggs)',
    name_am: 'እንቁላል ሩቅ',
    calories_per_serving: 320,
    protein_g: 22,
    carbs_g: 2,
    fat_g: 26,
    serving_description: '2 eggs',
    is_fasting_friendly: false,
    category: 'breakfast',
    image_url: '/foods/eggs.jpg',
  },
  {
    name_en: 'Teff with Yogurt',
    name_am: 'ተፍ ዐብ',
    calories_per_serving: 300,
    protein_g: 12,
    carbs_g: 45,
    fat_g: 6,
    serving_description: '1 cup with yogurt',
    is_fasting_friendly: false,
    category: 'breakfast',
    image_url: '/foods/teff-yogurt.jpg',
  },
];
